spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-provider
server:
  port: 7700
eureka:
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-provider7000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
---
spring:
  profiles: test
  application:
    name: spring-cloud-provider
server:
  port: 8800
eureka:
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-provider7000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka/
